const settings = {
  MAX_ENERGY: 3,
  BONUS_FOR_INVITE: 25,
  BONUS_FOR_INVITE_WITH_PREMIUM: 50,
  ENERGY_RECOVERY_TIME_SECONDS: 60 * 60 * 1.5,
  MAX_DIFF_SECONDS: 180,
  MAX_SCORE_IN_GAME: 140,
};

export { settings };
