const settings = {
  MAX_ENERGY: 3,
  BONUS_FOR_INVITE: 50,
  BONUS_FOR_INVITE_WITH_PREMIUM: 100,
  ENERGY_RECOVERY_TIME_SECONDS: 60 * 60 * 2,
  MAX_DIFF_SECONDS: 180,
  MAX_SCORE_IN_GAME: 140,
};

export { settings };
